### PR TITLE
Updated SDK, added default values and updated checkout.

### PR DESCRIPTION
**Pull request by woutse**

### CODE REVIEW

**Comment by woutse** [comment]
[paynlpaymentmethods_3.4.0.zip](https://github.com/paynl/prestashop1.7-plugin/files/4987707/paynlpaymentmethods_3.4.0.zip)

**Comment by woutse** [comment]
[paynlpaymentmethods_3.4.0.zip](https://github.com/paynl/prestashop1.7-plugin/files/4988036/paynlpaymentmethods_3.4.0.zip)

**Comment by woutse** [comment]
[paynlpaymentmethods_3.4.0.zip](https://github.com/paynl/prestashop1.7-plugin/files/4995022/paynlpaymentmethods_3.4.0.zip)

**Review by annevelden — CHANGES_REQUESTED** [review]
check ticket for notes

**Review by annevelden — APPROVED** [review]

**Review by kevinverschoor — APPROVED** [review]

**Pull request merged**
